-- Schema PostgreSQL para o projeto Kintal Lanches.
-- Execute este arquivo no Supabase SQL Editor.

create table if not exists admins (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  name text not null default 'Administrador',
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text default 'burger',
  sort_order integer not null default 0,
  active integer not null default 1
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  image text not null default '',
  price numeric(10,2) not null default 0,
  promo_price numeric(10,2),
  category_id bigint references categories(id) on delete set null,
  active integer not null default 1,
  featured integer not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists addons (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  active integer not null default 1,
  sort_order integer not null default 0
);

create table if not exists product_addons (
  product_id bigint not null references products(id) on delete cascade,
  addon_id bigint not null references addons(id) on delete cascade,
  primary key (product_id, addon_id)
);

create table if not exists promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  image text not null default '',
  promo_price numeric(10,2),
  start_date timestamptz,
  end_date timestamptz,
  active integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  order_type text not null default 'delivery',
  address_street text not null default '',
  address_number text not null default '',
  address_complement text not null default '',
  address_neighborhood text not null default '',
  address_reference text not null default '',
  payment_method text not null default 'pix',
  change_for numeric(10,2),
  delivery_fee numeric(10,2) not null default 0,
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  notes text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  quantity integer not null default 1,
  unit_price numeric(10,2) not null default 0,
  addons_json jsonb not null default '[]'::jsonb,
  notes text not null default ''
);

create table if not exists settings (
  key text primary key,
  value text
);

create table if not exists business_hours (
  id bigint generated by default as identity primary key,
  day_of_week integer not null unique,
  open_time text not null default '18:00',
  close_time text not null default '23:30',
  closed integer not null default 0
);

create index if not exists idx_products_category on products(category_id);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_created on orders(created_at);
create index if not exists idx_order_items_order on order_items(order_id);

-- Confirma as tabelas criadas.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'admins', 'categories', 'products', 'addons', 'product_addons',
    'promotions', 'customers', 'orders', 'order_items', 'settings',
    'business_hours'
  )
order by table_name;
